### ISSUE TITLE
Use array indices as IDs

### ISSUE THREAD

**Issue by ColemanGariety** [sarajs/Sara#49]

**Comment by ColemanGariety** [comment]
@mkgh good or bad idea?

if the database return in different order, the app is fucked. Is order okay to rely on?

**Comment by topokel** [comment]
What would make the database return out of order?

**Comment by ColemanGariety** [comment]
@mkgh I'm not sure, I just see most ORMs using `_id` or `id`, while object oriented programming has a perfectly good way to identify an object in a collection `Todos[todoId]`
