### ISSUE TITLE
Todo example does not work out of the box

### ISSUE THREAD

**Issue by topokel** [sarajs/Sara#52]
Upon pulling 57d142f583503679b15001bfaacf2fdd0aa704a2 and performing the following

``` bash
sudo npm install -g gulp
sudo npm install 
cd examples/todo-example && npm install
cd ../.. && gulp
```

gulp runs successfully; however, nothing is served to localhost:1337. Running node on `examples/todo-example/app.js` manually results in npm getting all whiny `Error: Cannot find module 'sara'` because it's not in the package.json. Using `npm install https://github.com/sarajs/Sara/tarball/master` fixes the issue but isn't terribly helpful for developing. I instead pointed all the `require('sara')`'s to the root of the repository and the react app worked great until

``` bash
1337
Listening on port 1337.

TypeError: Object #<Object> has no method 'initKeyboardEvent'
    at new Event (/home/michael/Sara/lib/sara/event.js:38:53)
    at Socket.<anonymous> (/home/michael/Sara/lib/sara/server.js:202:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onPacket (/home/michael/Sara/node_modules/engine.io/lib/socket.js:102:14)
    at XHR.EventEmitter.emit (events.js:95:17)
    at XHR.Transport.onPacket (/home/michael/Sara/node_modules/engine.io/lib/transport.js:95:8)
    at /home/michael/Sara/node_modules/engine.io/lib/transports/polling.js:181:10
    at Object.exports.decodePayload (/home/michael/Sara/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:152:19)
    at XHR.Polling.onData (/home/michael/Sara/node_modules/engine.io/lib/transports/polling.js:174:10)
    at IncomingMessage.onEnd (/home/michael/Sara/node_modules/engine.io/lib/transports/polling.js:145:12)
```

npm is saying `npm http GET http://github.com/sarajs/jsdom/tarball/master` so what do you think could be causing this?

**Comment by ColemanGariety** [comment]
@mkgh first issue is my fault, I'm ignoring the node_module folder yet inside I have a fake module which just exports `../../../..`. I'll add in my next commit.

As for the initKeyboardEvent method, I'm not sure. If my jsdom fork weren't loading correctly it would simply say it couldn't `new KeyboardEvent` because [they're defined in the same place](https://github.com/sarajs/jsdom/blob/master/lib/jsdom/level3/events.js#L252).

Can you console.log `Object` and tell me what it is?

**Comment by topokel** [comment]
Fixed by 6602b64ff612dc1398fa2790a1ab4e6ca46c899c

**Comment by ColemanGariety** [comment]
@mkgh including the keybaord event error?

And I think I figured that one out too, Chrome doesn't support the pluralized version while using `document.createEvents` which will be fixed in my next commit.

**Comment by topokel** [comment]
Yeah it all works out the box on my machine now 
![screenshot from 2014-02-05 01 21 38](https://f.cloud.github.com/assets/2965148/2085541/2d72f974-8e47-11e3-84e7-f587e3117447.png)

**Comment by ColemanGariety** [comment]
:clap:

**Comment by ColemanGariety** [comment]
@mkgh keep in mind there are still lots of bugs everywhere

**Comment by topokel** [comment]
![bee keeper suit](http://lghttp.17653.nexcesscdn.net/808B16/cdn_images/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/h/b/hb125-3.jpg)
my body is ready.
